### ISSUE TITLE
Panic on nil pointers in structs

### ISSUE THREAD

**Issue by tom-seechange** [dranikpg/dto-mapper#1]
Hi,

When mapping from a struct, to a struct, either of which contain nil pointers, the mapValue function will panic on the following line:

`tk, fk := toRv.Type().Kind(), fromRv.Type().Kind()`

This is due to a nil pointer dereference

The following code snippet skips mapValues if either side is nil:

`func (m *Mapper) mapValue(toRv, fromRv reflect.Value) (returnError error) {
	if !toRv.IsValid() || !fromRv.IsValid() {
		return
	}`

That works for me but unsure of any unintended consequences.

Thanks,

Tom

**Comment by dranikpg** [comment]
Hi!

Thanks for reporting the issue. This is indeed a bug

Would you mind checking out ac79c39a75fcccb5db827c8ac8fe09d409e73b2d? I hope this should fix your issues. If it does, I'll release a patch shortly

**Comment by dranikpg** [comment]
Closed by v0.1.1
